# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
