# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160121_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
