language: python
python:
- 3.5.0
services:
- postgresql
- memcached
env:
- DJANGO=1.9.1
before_install:
- export DJANGO_SETTINGS_MODULE=giftlist.travis-settings
- export PYTHONPATH=$HOME/builds/jeffnb/giftlist-api
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE giftlist;" -U postgres
- python manage.py migrate
script:
- coverage run --source='.' manage.py test lists api
after_success:
- coveralls
