language: python
python:
- 3.5.0
- 3.5.1
services:
- postgresql
env:
- DJANGO=1.9.1
before_install:
- export DJANGO_SETTINGS_MODULE=giftlist.travis-settings
- export PYTHONPATH=$HOME/builds/jeffnb/giftlist-api
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE giftlist;" -U postgres
- python manage.py migrate
script:
- coverage run --source='.' manage.py test users lists api
after_success:
- coveralls
deploy:
  provider: heroku
  api-key:
    - secure: "SdX45a90/glUK793cjHb5sHyEjyNzE5+Q/xocPy4PGzjuKWe+HuO+VUXtiMw2jWTOM6uW3tX5DkxyEMF3mrpKdyDQqd89MS7VzsFHWFUzJIGrureQu3LcfeXD2qCKeCoUTLx0vJKnWqHOs+EGTbkUJud4f/EdCi0NPjmjCJ28EfHnkItF8wvuu72OsYvMdHDlYJwolovwadfSvxUp+G2D6AvHID5wvmA5FauG0UZyrjpzG6ITZZ3Lsrgnl55OFLzXGpXs4N7Vu1uXLY1GO8ay49vEZJm0cKf0+9HVNXyfPGGwCNMhEPj5p5KRMGN1ia7UaQYauGXFcGbMR1yfYZR+TjFsy240sYHCcCtPKXufq44WH/aggxAYsMTJ5K1wmoIlnAxm9uh5znoHWhW7yFhlEB/FuDWzbQAYUs9NntOSzdOL2NWLCDSmxG5ZW0gHDj0RHMdhcP00Gno3f+CxzC798MwdKV28d2Pr+B8ON1wNlehR/ZWbvcQkT8vplR6sb3SoYtX7bwLRyfvFE+wb0dug0/+YPGCeyD2dWqJZmwXO654Xz3ufadjf2nGtZOooEn9g1FYQsvKC1t4c8f0icDG4D/WUX7ZLw2/96kGKCkEEUoHE+oZ6muo52o79p8v7/VoIanyrNvRW/8TnHoeaP0FsQGIsFvqRl6qVPjez2y4VQw="
  app: fierce-stream-5433
  run: "python manage.py migrate"