# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_eventlist_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pledge',
            name='status',
            field=models.CharField(choices=[('Captured', 'captured'), ('Refunded', 'refunded'), ('Disputed', 'disputed')], default='captured', max_length=15),
            preserve_default=False,
        ),
    ]
