# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20160107_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='status',
            field=models.CharField(choices=[('Captured', 'captured'), ('Refunded', 'refunded'), ('Disputed', 'disputed'), ('Intial', 'initial')], default='Intial', max_length=15),
        ),
    ]
