# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20160107_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='charge_id',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
